SELECT
    MEMBER_ID,
    MEMBER_NAME,
    GENDER,
    DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH
FROM
    MEMBER_PROFILE
WHERE
    DATE(DATE_OF_BIRTH) LIKE '____-03%'
    AND GENDER = 'W'
    AND TLNO LIKE '%'
ORDER BY
    MEMBER_ID ASC;