SELECT DISTINCT
   A.ITEM_ID,
   A.ITEM_NAME,
   A.RARITY
FROM
    ITEM_INFO A
JOIN
    (SELECT DISTINCT
        D.ITEM_ID AS ITEM_ID
    FROM
        ITEM_INFO C
    JOIN 
        ITEM_TREE D ON C.ITEM_ID=D.PARENT_ITEM_ID
    WHERE
        C.RARITY = 'RARE') AS B ON A.ITEM_ID=B.ITEM_ID
ORDER BY
    A.ITEM_ID DESC;