SELECT DISTINCT
    D.ID,
    D.EMAIL,
    D.FIRST_NAME,
    D.LAST_NAME
FROM
    DEVELOPERS D
JOIN
    SKILLCODES S ON S.NAME='C#' OR S.NAME='Python'
WHERE
    (D.SKILL_CODE&S.CODE)>1
ORDER BY
    ID ASC;