SELECT
    SUM(G.SCORE) AS SCORE,
    G.EMP_NO AS EMP_NO,
    E.EMP_NAME AS EMP_NAME,
    E.POSITION AS POSITION,
    E.EMAIL AS EMAIL
FROM 
    HR_GRADE G
JOIN
    HR_EMPLOYEES E ON G.EMP_NO=E.EMP_NO
GROUP BY
    EMP_NO
ORDER BY
    SCORE DESC
LIMIT 1
