SELECT 
TITLE, 
USED_GOODS_BOARD.BOARD_ID AS BOARD_ID,
REPLY_ID, USED_GOODS_REPLY.WRITER_ID AS WRITER_ID, 
USED_GOODS_REPLY.CONTENTS AS CONTENTS, 
DATE_FORMAT(USED_GOODS_REPLY.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM
USED_GOODS_BOARD
JOIN USED_GOODS_REPLY ON USED_GOODS_BOARD.BOARD_ID=USED_GOODS_REPLY.BOARD_ID
AND USED_GOODS_BOARD.CREATED_DATE LIKE '2022-10%'
ORDER BY CREATED_DATE ASC, TITLE ASC;
